version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-2.7
      - test-3.4
      - test-3.5
      - test-3.6
      - black

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: |
        GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
          sudo -E pip install -r requirements.txt pytest
  - run:
      name: Test
      command: PYTHONPATH=. pytest tests

jobs:
  test-2.7:
    <<: *defaults
    docker:
    - image: circleci/python:2.7
    - image: mongo:3.2.19
  test-3.4:
    <<: *defaults
    docker:
    - image: circleci/python:3.4
  test-3.5:
    <<: *defaults
    docker:
    - image: circleci/python:3.5
  test-3.6:
    <<: *defaults
    docker:
    - image: circleci/python:3.6
  black:
    docker:
    - image: circleci/python:3.6
    working_directory: ~/code
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: sudo -E pip install black
    - run:
        name: Test
        command: black --check .
